kind: stack
description: Stack of OBS Studio non-Qt dependencies

depends:
- components/ffmpeg.bst
- components/jansson.bst
- components/libajantv2.bst
- components/libdatachannel.bst
- components/libqrcodegencpp.bst
- components/librist.bst
- components/luajit.bst
- components/mbedtls.bst
- components/nv-codec.bst
- components/srt.bst
- components/svt-av1.bst
- components/x264.bst
- qsv-maybe.bst
