name: Push
run-name: ${{ github.ref_name }} push run
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build-project:
    name: Build Project
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
    uses: ./.github/workflows/build-project.yaml
    with:
      arch: ${{ matrix.arch }}
      upload-artifacts: ${{ github.ref == 'refs/heads/master' }}

  check-code:
    name: Check Code Changes
    uses: ./.github/workflows/check-code.yaml
